# Reusable workflow for releases; to eject, you can replace this file with
# https://github.com/ryansonshine/ryansonshine/blob/main/.github/workflows/release.yml
name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test --silent
      - name: Build
        run: npm run build
      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish if version is new
        id: publish
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          PKG_NAME=$(node -p "require('./package.json').name")
          REMOTE_VERSION=$(npm view "$PKG_NAME" version || echo '0.0.0')
          echo "Local: $CURRENT_VERSION | Remote: $REMOTE_VERSION"
          if [ "$CURRENT_VERSION" = "$REMOTE_VERSION" ]; then
            echo "Version unchanged. Skipping publish."
            echo "published=false" >> $GITHUB_OUTPUT
          else
            npm publish --access public
            echo "published=true" >> $GITHUB_OUTPUT
          fi
      - name: Post-publish info
        if: steps.publish.outputs.published == 'true'
        run: echo "Published $(node -p "require('./package.json').name")@$(node -p "require('./package.json').version")"
